# Demo {#demo}

This is just a demo for the **software workshop**.

## Importing a Concourse

```{r make-cards, include = FALSE, eval=FALSE}
make.distribution(nstat=78, max.bin=7)
q_concourse <- import.q.concourse(  # import concourse
  q.concourse.dir = "../schumpermas/keyneson/keyneson-sample/keyneson-concourse/",
  languages = c("english", "german")
)
q_sampling_structure <- read.csv(  # read in sampling structure
  file = "../schumpermas/keyneson/keyneson-sample/sampling-structure.csv",
  fileEncoding = "UTF-8"  # should not be necessary, all data is ascii
)
q_distribution <- as.integer(c(  # set up distribution
  "-7" = 1,  # these names are crap, they don't really work, maybe rather make this a matrix if you really want names
  "-6" = 1,
  "-5" = 2,
  "-4" = 4,
  "-3" = 6,
  "-2" = 9,
  "-1" = 10,
  "0" = 11,
   "1" = 10,
   "2" = 9,
   "3" = 6,
   "4" = 4,
   "5" = 2,
   "6" = 1,
   "7" = 1
))
q_set <- build.q.set(
  q.concourse = q_concourse,
  q.sample = q_sampling_structure$handle,
  q.distribution = q_distribution
)
names(dimnames(q_set)) <- c("items", "languages")
make.cards(q.set = q_set[sort(row.names(q_set)), ], 
           study.language = "english", 
           output.pdf = TRUE, 
           show.handles = TRUE,
           file.name = "cards-civicon_researcher",
           duplex.double = TRUE)
```


```{r prep, include = FALSE}
# devtools::install_github(repo = "maxheld83/qmethod", ref = "more-rot", force = TRUE)
knitr::opts_chunk$set(tidy = TRUE, cache = TRUE, echo = FALSE, message = FALSE, fig.width = 10, fig.height = 9)  # tidy formats code nicely in echo
options(digits = 2)  # display only 2 digits in knitr output
options(scipen = 999)
library(qmethod)
library(pensieve)
```

```{r data-import, include = FALSE}
sorts <- civicon_2014$qData$sorts[,,"before"]
head(sorts)
```

## Correlations

```{r cor, fig.cap="Correlations"}
cors <- correlate(sorts = sorts, method = "spearman", use = "pairwise.complete.obs")
plot(cors)
```

```{r check-cors, include = FALSE}
check(cors)
str(cors)
# cors["Christian", "Claus"] <- 2
# check(cors)
```


# Parallel Analysis

```{r paran, fig.cap="Parallel Analysis"}
nfac <- q.nfactors(dataset = sorts, 
                   cutoff = 5, 
                   siglevel = 0.05, 
                   quietly = TRUE,
                   cor.method = "spearman",
                   iterations = 10000)
plot(nfac$screeplot)
ret_fac <- 3
```


# Extraction

```{r extraction, fig.cap="Unrotated Loadings", include = FALSE, eval=FALSE}
loas <- extract(cors = cors, nfactors = ret_fac, fa_type = "pca")
# help(loas)
pensieve::plot.QLoas(x = loas, by = "people", r2 = TRUE)
```

```{r rotation}
res <- qmethod(dataset = sorts, 
               nfactors = ret_fac, 
               rotation = "varimax",
               forced = TRUE,
               cor.method = "spearman",
               allow.confounded = TRUE,
               threshold = "none")
# res <- q.fnames(results = res, fnames = c("resentment", "moderate", "critical"))
# res <- q.fcolors(results = res)
q.loaplot(results = res,
          quietly = FALSE, 
          names = TRUE, 
          points = TRUE, 
          alpha = 1, 
          grid = TRUE,
          rug = TRUE,
          maxvals = FALSE)
q.compplot(results = res)
```


```{r scoring, include = FALSE, eval=FALSE}
q.scoreplot.num(results = res, factor = "resentment")
q.scoreplot.ord(results = res, factor = "resentment")
```





