# Measurement {#measurement}

<!-- long title would be: how and why we measure operant subjectivity -->


<!-- Table: (\#tab:var-meas-ded) Variations of Measuring Operant Subjectivity (ipsative) -->

<!-- +---------------+---------------+---------------+--------------------+---------------+--------------------+ -->
<!-- | \             | \             | \             | *Constraints* \    | \ |  \ |  -->
<!-- | "Open Space"       | Fruit         | Price         | Advantages         |  -->
<!-- Price         | Advantages         |  -->
<!-- +===============+===============+===============+====================+===============+====================+ -->
<!-- | Bananas       | $1.34         | - built-in wrapper | Bananas       | $1.34 | - -->
<!-- built-in wrapper | |               |               | - bright color     | | | |  -->
<!-- +---------------+---------------+--------------------+---------------+---------------+--------------------+1 -->
<!-- | Bananas       | $1.34         | - built-in wrapper | Bananas       | $1.34 | - -->
<!-- built-in wrapper | |               |               | - bright color     | | | |  -->
<!-- +---------------+---------------+--------------------+---------------+---------------+--------------------+ -->


<!-- ----------- ------- --------------- ------------------------- First    row 12.0  -->
<!-- Example of a row that spans multiple lines. -->

<!-- Second    row                 5.0 Here's another one. Note the blank line  -->
<!-- between rows. ----------- ------- --------------- ------------------------- -->


<!-- RGT, despite the acronym isn't really R methodology. RGT is also idiographic  -->
<!-- (not nomothetic), as is often suggested R would be -->


## Q-Honeycomb --- Measuring Operant Subjectivity with Hexagonal Tiling

*Maximilian Held, Verena Kasztantowicz, Sabine Pfeiffer*

Because Q Methodology implies an *ipsative* measurement, sorting procedures must ensure that participants evaluate items *relatively* against one another, and not *objectively* against some external standard.
At the same time, Q researchers may want to spread out the Q rankings, or even allow free distributions, both of which can degrade the procedure to a rating measurement.
These trade-offs only become more acute, when sorts are gathered online, where screen real estate is scarce and the careful ipsative weighting of items may be difficult to ensure already [@liston2015a-comparative-s].

Such honeycomb structures are an efficient way to regularly tesselate planes [@hales2001the-honeycomb-c], which is why they are sometimes found in nature and engineering.
This optimal geometry may also improve the Q-sorting procedure.
Because the edges of a regular hexagon are equidistant from the center, participants may be able to sort the items more precisely, without distortions around the rectangular corners.
In a *pointy-topped* orientation, because every other row is offset vertically, a hexagonal grid also doubles the ranking granularity of Q Sorts for a given number of columns.
Lastly, because such a honeycomb structure makes the *vertical* orientation slightly more difficult, it may strengthen the ipsative weighting of items, and allow more spread out, or free distributions.

Initial experiences with hexagonal grid data gathering are reported, and custom software for gathering, printing and reporting hexagonal Q grids is presented.
