---
title: "Item Generation and Sampling"
author: "Maximilian Held"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: held_library.bib
vignette: >
  %\VignetteIndexEntry{Item Generation and Sampling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Good, evocative items lie at the heart of a Q study.
In fact, akin to the old computer science adage of  *"garbage-in / garbage-out"*, the quality of the *items* strictly limits the insights that may be gleaned from the entire study.

Generating and selecting good items is at least half science, half tradecraft.
There are some standards and frameworks that can structure your item generation and sampling, but -- for now at least -- it still requires a lot of experience, intuition and knowledge of the domain in question.

`pensieve` supports this stage of a Q study in a number of ways:

1. Items **generation and selection** can be fully documented inside of `pensieve`, making the process transparent, reproducible and easy to iterate over.
2. Items can be **professionally typeset**, and stored in `pensieve`, so that participants and researchers alike both see the items in the *same, definitive form*, be they text or images.
3. Arbitrary **additional information** can be stored alongside the items for later "R-way" analysis.

Items and related information are stored in a domain-specific format in `pensieve`, a list of S3 class `psItems`.
You can use the package entirely without `psItems`, though providing additional information about the items is highly recommended.
For example, providing the full item text (or image) enhances some of the downstream plots.


### `psItemContent`

`psItemContent` is the most important element of `psItems`.
It stores the **full wording** of items, or, in the case of image items or other assets the **paths to the binary sources**.
`psItemContent` is easily created from a character vector.

If it is named, these names are retained as **item handles**.
Such handles provide a succinct way to refer to items, and can also be displayed in plots and tables.
In contrast to the conventionally used statement numbers ("`sta_27`"), I recommend short, meaningful labels.
The handles are *researcher-facing*, they are *not* part of the items and are never shown to participants.

For an example, let's take the Lipset items from @Brown1980, with some hand-crafted item handles.


<!-- TODO read in lipset items here -->

```{r}
library(pensieve)
lipset <- NULL
lipset$items <- qmethod::lipset$ltext$text
names(lipset$items) <- c(
  "accept_improvements_lower_classes",
  "expected_2_improve",
  "success_resented",
  "expect_fair_treatment",
  "no_revolutionary_inclinations",
  "moderation",
  "retain_high_place",
  "wealth_deserves",
  "eliminate_privileged",
  "accept_aristocratic",
  "govnm_secrets_ok",
  "no_secrets",
  "complete_4_success",
  "social_distinction",
  "vigilantism",
  "close_2_uk",
  "prefer_voluntary_help",
  "no_wealth_for_wealth",
  "promoting_underdog",
  "like_welfare_state",
  "race_4_success",
  "corruption_accepted",
  "dif_laws_rich_poor",
  "lack_of_respect_police",
  "trust_in_police",
  "self_made",
  "respect_elite",
  "middle_of_road",
  "afterlife",
  "civil_liberties",
  "virtue",
  "raise_depressed",
  "get_ahead"
  )
lipset$items <- psItemContent(items = lipset$items, lang = "en-US")
```

You'll notice that `psItemContent()` allows you to specify a language, which can improve the typesetting results later on.
To learn more about acceptable language codes, see the help for `psItemContent()`.

`psItemContent()` also allows you to set the way items are typeset (or rendered).
This defaults to the settings for printing items on standard-issue business cards, but you can provide arbitrary dimensions and margins.
Just keep in mind that not all options may meet the requirement that your item text *can* in fact be typeset to a *single* page.

