---
layout: post
title: Retention Criteria
published: false
categories:
- blog
- research
lang: en
comments: true
tags:
- statistics
- qmethod
- Q Methodology
- rstats
bibliography: ../../held-library/held_library.bib
---

I do remain troubled by what Peter Schmolck has aptly called "critique of randomness" (better in German: Zufallskritik), or what might otherwise be known as significance testing. I can only assure all members of this list, that this concern is less motivated by some commitment to R orthodoxy (though I don't think that would invalidate my concern per se), but is rather rooted in the particulars of my research project (something Q methodologists appear to be keen of): Given an equally complex and politicised research topic (taxation and economics), I am wary of allowing myself as a researcher to much interpretive (or abductive) leeway.
I have opinions on these issues, and what is wrong with our popular understanding of them, and so must be careful that I do not work them into the analysis. Somewhat objective factor retention criteria are one of the ways in which I am seeking to constrain my interpretation of participants shared subjectivities (as Q methodology should do – it is not critical discourse analysis as was recently pointed out here).

I plan to return to the issue of factor retention criteria (especially parallel analysis) with a longer, more thorough piece shortly.
I hope to (pre-emptively?) take on Bob Braswell's issue 4):

4) Statistical rules about not keeping "too many" factors are based on avoiding the danger of interpreting a factor that isn't "real" (a factor based on noise in the data and random correlation rather than real communality). The Q methodologist almost always faces the inverse problem rather than this one.

For now, let me just rebut one preliminary point that is relevant here.

Bob Braswell and others have pointed out that a) Q Methodology does not customarily require random sampling, that b) Eigenvalue and communalities-based criteria are affected by sampling and that therefore, c) these criteria may not be informative or adequate for Q.
I agree that -- as previously written -- in Q, we are not less interested in a factor because it is shared by fewer people (as may be common in R research), more so, because our samples are non-random (though I can presently see no reason why Q studies should not be done with random samples of people-variables).
This latter argument is concerned -- rightfully -- with avoiding false-negatives, that is, to avoid not-interpreting some factor that is actually expressive of some shared subjectivity.
Parallel analysis (and other objective criteria) are concerned with avoiding false-positives, that is, avoiding an interpretation of a "random" scree factor (as Cattell put it).
Both have their place in science, though customarily, avoiding false-negatives is preferred over avoiding false-positives (that is the logic of falsification).

I reiterate this distinction to point out that objective criteria (of factor retention) do not somehow skew or nullify a fully abductive interpretation of those factors retained, as seems to be somehow implied.
It simply restricts itself – for now – to an interpretation of those factors about which
